# Generated by Django 5.0.9 on 2024-09-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='businesscallingdata',
            table='accounts_BusinessCallingData',
        ),
    ]
