# Generated by Django 5.0.9 on 2024-09-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_businesscallingdata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='businesscallingdata',
            table='accounts_BusinessCallingData',
        ),
    ]
