# Generated by Django 5.0.9 on 2024-09-17 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_businesscallingdata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='businesscallingdata',
            table='BusinessCallingData',
        ),
        migrations.AlterModelTable(
            name='daywisesummarised',
            table='day_wise_summarised_final',
        ),
    ]
