# Generated by Django 5.0.9 on 2024-09-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mst_UserTbl',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('UserID', models.IntegerField(primary_key=True, serialize=False)),
                ('EmpID', models.CharField(max_length=10)),
                ('DesignationID', models.PositiveSmallIntegerField()),
                ('UserName', models.CharField(max_length=50)),
                ('UserCode', models.CharField(max_length=20, unique=True)),
                ('ContactNo', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=150, null=True, unique=True)),
                ('Hoid', models.PositiveSmallIntegerField()),
                ('DivisionID', models.CharField(max_length=10)),
                ('RegionID', models.CharField(max_length=10)),
                ('HubID', models.CharField(max_length=20)),
                ('BranchID', models.CharField(max_length=50)),
                ('BranchJoinDate', models.CharField(max_length=30)),
                ('BranchExitDate', models.CharField(max_length=30)),
                ('Comment', models.CharField(max_length=60)),
                ('IsActive', models.CharField(max_length=30)),
                ('CreatedBy', models.FloatField(null=True)),
                ('CreatedDate', models.CharField(max_length=40)),
                ('UpdatedBy', models.CharField(max_length=10)),
                ('UpdatedDate', models.CharField(max_length=40)),
                ('Locked', models.CharField(max_length=10)),
                ('LastPasswordDate', models.CharField(max_length=40)),
                ('BUType', models.FloatField(null=True)),
                ('Buid', models.FloatField(null=True)),
                ('IsLoggedin', models.CharField(max_length=10)),
                ('DeviceNo', models.CharField(max_length=80)),
                ('Session_Token_Id', models.CharField(max_length=50)),
                ('LoginDevice', models.CharField(max_length=50)),
                ('New', models.FloatField(null=True)),
                ('NewBranchId', models.FloatField(null=True)),
                ('EmpDOB', models.CharField(max_length=30)),
                ('GLAccountId', models.FloatField(null=True)),
                ('AccountId', models.FloatField(null=True)),
                ('IsDropout', models.CharField(max_length=10)),
                ('DropoutDate', models.CharField(max_length=40)),
                ('IsHelpDeskStaff', models.CharField(max_length=10)),
                ('registration_authenticated', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('deactivated', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
