# Generated by Django 5.0.9 on 2024-09-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mst_usertbl',
            options={'managed': False},
        ),
    ]
