# Generated by Django 5.0.9 on 2024-09-13 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_mst_usertbl_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='calling_number_list',
            fields=[
                ('UserID', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='calling_obj', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('CallingNumber', models.CharField(max_length=20)),
                ('Is_active', models.BooleanField(default=True)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('agent_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'accounts_calling_number_list',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='mst_usertbl',
            table='accounts_Mst_UserTbl',
        ),
    ]
