# Generated by Django 5.0.9 on 2024-09-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_calling_number_list_alter_mst_usertbl_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_details',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(blank=True, max_length=100, null=True)),
                ('task_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('assigned_role', models.CharField(max_length=100)),
                ('complete_status', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('review', models.CharField(blank=True, max_length=1000, null=True)),
                ('feedback', models.CharField(blank=True, max_length=1000, null=True)),
                ('priority', models.IntegerField(blank=True, choices=[(1, 'Immediate'), (2, 'High'), (3, 'Medium'), (4, 'Low')], default=1, null=True)),
                ('deadline_track', models.JSONField()),
                ('review_track', models.JSONField()),
                ('feedback_track', models.JSONField()),
                ('t_info', models.CharField(blank=True, max_length=50, null=True)),
                ('T_Info_ID', models.IntegerField(blank=True, null=True)),
                ('bulk_task_status', models.IntegerField(blank=True, choices=[(0, 'REGULAR TASK'), (1, 'RELATIVE BULK TASK'), (2, 'NOT RELATIVE BULK TASK')], default=0, null=True)),
                ('bulk_task_whatsapp_queue', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'accounts_task_details',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='calling_number_list',
            options={},
        ),
    ]
