# Generated by Django 5.0.9 on 2024-09-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_mst_usertbl_table'),
        ('user', '0004_task_details_alter_calling_number_list_options'),
    ]

    operations = [
    ]
