# Generated by Django 5.0.9 on 2024-09-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_merge_20240916_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calling_number_list',
            options={'managed': False},
        ),
    ]
