# Generated by Django 5.0.9 on 2024-09-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_followup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCallingDataHistory',
            fields=[
                ('Srno', models.AutoField(primary_key=True, serialize=False)),
                ('DisbursementID', models.IntegerField()),
                ('LastDialledDate', models.DateField(auto_now_add=True, null=True)),
                ('task_id', models.CharField(default='', max_length=100)),
                ('task_assigned_to', models.IntegerField()),
                ('task_status', models.CharField(default='', max_length=100)),
                ('task_completion_date', models.DateField(auto_now_add=True, null=True)),
                ('feedback_response', models.CharField(default='', max_length=100)),
                ('feedback_code', models.BooleanField(default=True)),
                ('call_primary_id', models.IntegerField(null=True)),
                ('call_initiated_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'businesscallingdatahistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackObservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='', max_length=1000)),
            ],
            options={
                'db_table': 'FeedbackObservations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Retention_Calling_History',
            fields=[
                ('Srno', models.AutoField(primary_key=True, serialize=False)),
                ('DisbursementID', models.IntegerField()),
                ('LastDialledDate', models.DateField(auto_now_add=True, null=True)),
                ('task_id', models.CharField(default='', max_length=100)),
                ('task_assigned_to', models.IntegerField()),
                ('task_status', models.CharField(default='', max_length=100)),
                ('task_completion_date', models.DateField(auto_now_add=True, null=True)),
                ('feedback_response', models.CharField(default='', max_length=100)),
                ('feedback_code', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Retention_Calling_History',
                'managed': False,
            },
        ),
    ]
