# Generated by Django 5.0.9 on 2024-09-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_followup', '0002_businesscallingdatahistory_feedbackobservations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPromiseDataHistory',
            fields=[
                ('Srno', models.AutoField(primary_key=True, serialize=False)),
                ('DisbursementID', models.IntegerField()),
                ('LastDialledDate', models.DateField(auto_now_add=True, null=True)),
                ('task_id', models.CharField(default='', max_length=100)),
                ('task_assigned_to', models.IntegerField()),
                ('task_status', models.CharField(default='', max_length=100)),
                ('task_completion_date', models.DateField(auto_now_add=True, null=True)),
                ('feedback_response', models.CharField(default='', max_length=100)),
                ('feedback_code', models.BooleanField(default=True)),
                ('promise_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'PendingPromiseData_History',
                'managed': False,
            },
        ),
    ]
